image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - apt update
  - apt-get install python3-pyqt4 -y
  - pip install virtualenv dwave-ocean-sdk numpy 
  - virtualenv venv
  - source venv/bin/activate

test_gui:
  script:
  - python GUI/jufo-gui.py test
  - pip install tox flake8
  - tox -e py36,flake8 

run_gui:
  script:
  - python GUI/jufo-gui.py bdist_wheel
  - pip install dist/*
  artifacts:
    paths:
    - dist/*.whl
